### PR TITLE
- Xcode project rewrite (too many deprecations and UI changes of iOS …

### PR DESCRIPTION
**Pull request by benstadin**
…itself, old project didn't anymore work with latest Xcode 7)

- fixed building for ios 9
- added ios_deployment_target (default 8.0). Required because we need to set min version due to http://www.openradar.me/21724015
- disabled proguard (not required for hello example)
- pass sim to avian during make
- made 64 bit default
- added small build script to cleanly build avian and hello-ios for required target

### CODE REVIEW

**Comment by benstadin** [comment]
Project update without copyright notice.

**Comment by dicej** [comment]
Hi Ben,

Sorry for the delay on merging this; I had some issues updating Xcode to test it.

I had to apply this patch to actually build:

```diff
diff --git a/hello/hello.xcodeproj/project.pbxproj b/hello/hello.xcodeproj/project.pbxproj
index 41bc664..574f946 100644
--- a/hello/hello.xcodeproj/project.pbxproj
+++ b/hello/hello.xcodeproj/project.pbxproj
@@ -427,9 +427,13 @@
 				ARCHS = "$(ARCHS_STANDARD)";
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				ENABLE_BITCODE = NO;
-				HEADER_SEARCH_PATHS = /System/Library/Frameworks/JavaVM.framework/Headers;
+				HEADER_SEARCH_PATHS = (
+					"$(JAVA_HOME)/include",
+					"$(JAVA_HOME)/include/darwin",
+				);
 				INFOPLIST_FILE = hello/Info.plist;
 				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
+				JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home;
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
 				OTHER_LDFLAGS = (
 					"-filelist",
@@ -448,9 +452,13 @@
 				ARCHS = "$(ARCHS_STANDARD)";
 				ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
 				ENABLE_BITCODE = NO;
-				HEADER_SEARCH_PATHS = /System/Library/Frameworks/JavaVM.framework/Headers;
+				HEADER_SEARCH_PATHS = (
+					"$(JAVA_HOME)/include",
+					"$(JAVA_HOME)/include/darwin",
+				);
 				INFOPLIST_FILE = hello/Info.plist;
 				IPHONEOS_DEPLOYMENT_TARGET = 8.0;
+				JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home;
 				LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
 				ONLY_ACTIVE_ARCH = YES;
 				OTHER_CFLAGS = "-DNS_BLOCK_ASSERTIONS=1";
diff --git a/makefile b/makefile
index 853ba1b..328644d 100644
--- a/makefile
+++ b/makefile
@@ -68,7 +68,7 @@ flags = -isysroot $(sdk-dir)/$(target)$(ios-version).sdk \
 
 cflags = $(flags) -D__IPHONE_OS_VERSION_MIN_REQUIRED=80000 -DRESOURCES \
 	-fobjc-abi-version=2 -fobjc-legacy-dispatch \
-	-I/System/Library/Frameworks/JavaVM.framework/Headers \
+	-I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin \
 	-mios-version-min=$(ios-version)
 
 ifeq ($(mode),debug)
```

I don't think that's related to your changes at all, but I wonder if that /System/Library/Frameworks/JavaVM.framework/Headers path needs to be changed, since it doesn't seem to exist in recent versions of OS X.  My patch only works for a specific version of Java, so it's not a good general solution.  How did you deal with this?

**Comment by blimmer** [comment]
TBH this was so old I don't remember at all. Sorry!

**Comment by dicej** [comment]
Oops, I meant @benstadin, not @blimmer, but thanks for responding so promptly, Ben L. :)

**Comment by benstadin** [comment]
Hi Joel,

I've blindly copy pasted this from the old project. I have Apple's Java 6 still installed, seems it no longer installs with new versions (I've upgraded since 10.8 to 10.10 without reinstall since).

I think it's ok to copy an old version with different license directly into the project. The MPL version (second jni.h link) from here and the discussion at Modzilla sounds like this is fine:
http://stackoverflow.com/questions/16998034/distribution-of-jni-h-with-my-software-package

As I remember, the iOS project is setting jni version 1.2. This fits with the old file from the link still. For other purposes than jni 1.2 a hint in the readme is maybe enough.
________________________________
Von: Joel Dice <notifications@github.com>
Gesendet: Dienstag, 3. November 2015 18:56:26
An: ReadyTalk/hello-ios
Cc: Stadin, Benjamin
Betreff: Re: [hello-ios] - Xcode project rewrite (too many deprecations and UI changes of iOS … (#5)


Hi Ben,

Sorry for the delay on merging this; I had some issues updating Xcode to test it.

I had to apply this patch to actually build:

diff --git a/hello/hello.xcodeproj/project.pbxproj b/hello/hello.xcodeproj/project.pbxproj
index 41bc664..574f946 100644
--- a/hello/hello.xcodeproj/project.pbxproj
+++ b/hello/hello.xcodeproj/project.pbxproj
@@ -427,9 +427,13 @@
                ARCHS = "$(ARCHS_STANDARD)";
                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                ENABLE_BITCODE = NO;
-               HEADER_SEARCH_PATHS = /System/Library/Frameworks/JavaVM.framework/Headers;
+               HEADER_SEARCH_PATHS = (
+                   "$(JAVA_HOME)/include",
+                   "$(JAVA_HOME)/include/darwin",
+               );
                INFOPLIST_FILE = hello/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = 8.0;
+               JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home;
                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                OTHER_LDFLAGS = (
                    "-filelist",
@@ -448,9 +452,13 @@
                ARCHS = "$(ARCHS_STANDARD)";
                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                ENABLE_BITCODE = NO;
-               HEADER_SEARCH_PATHS = /System/Library/Frameworks/JavaVM.framework/Headers;
+               HEADER_SEARCH_PATHS = (
+                   "$(JAVA_HOME)/include",
+                   "$(JAVA_HOME)/include/darwin",
+               );
                INFOPLIST_FILE = hello/Info.plist;
                IPHONEOS_DEPLOYMENT_TARGET = 8.0;
+               JAVA_HOME = /Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home;
                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
                ONLY_ACTIVE_ARCH = YES;
                OTHER_CFLAGS = "-DNS_BLOCK_ASSERTIONS=1";
diff --git a/makefile b/makefile
index 853ba1b..328644d 100644
--- a/makefile
+++ b/makefile
@@ -68,7 +68,7 @@ flags = -isysroot $(sdk-dir)/$(target)$(ios-version).sdk \

 cflags = $(flags) -D__IPHONE_OS_VERSION_MIN_REQUIRED=80000 -DRESOURCES \
    -fobjc-abi-version=2 -fobjc-legacy-dispatch \
-   -I/System/Library/Frameworks/JavaVM.framework/Headers \
+   -I$(JAVA_HOME)/include -I$(JAVA_HOME)/include/darwin \
    -mios-version-min=$(ios-version)

 ifeq ($(mode),debug)

I don't think that's related to your changes at all, but I wonder if that /System/Library/Frameworks/JavaVM.framework/Headers path needs to be changed, since it doesn't seem to exist in recent versions of OS X. My patch only works for a specific version of Java, so it's not a good general solution. How did you deal with this?

**Comment by dicej** [comment]
Yes, that's a good idea.  I'll go ahead and merge this as-is and work on including jni.h in Avian.

**Pull request merged**
